name: music_player
description: A simple music player app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^8.1.0
  flutter_riverpod: ^2.3.4
  fluttertoast: ^8.2.2
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  uuid: ^3.0.6
  flutter_animate: ^4.2.0+1
  firebase_core: ^2.15.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  connectivity_plus: ^5.0.2
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/songs/
